### ISSUE TITLE
Front & Rear Elevation Images

### ISSUE THREAD

**Issue by danner26** [netbox-community/devicetype-library#1036]
We are currently in the process of having a discussion on whether we will be able to include front and rear rack elevation images as part of this structured data. The maintainers are talking internally on how to best handle this, if possible, and consulting with legal counsel on the possible drawbacks of doing so.

We are evaluating these three following options: (feel free to comment if you have anymore)
1. Hosting the images within this repository, or more likely within another NetBox Community repository
2. Adding URL links to the structured data which reference the appropriate images URL
3. A combination of 1 and 2, where number option 2's URLs will point to option 1's repository

If you have any insight or thoughts about the topic, please feel free to drop a comment.

**Comment by mpsOxygen** [comment]
This would be amazing as having to add them by hand can be a real PITA. I think adding the image data in another repo would be the best way to go as URLs are prone to breaking in time, especially for smaller manufacturers.

**Comment by Wlanfr3ak** [comment]
I would also make my own photos for it, so that there are fewer problems with image rights. This is in any case something that I really missing so far in the repository and I have always inserted in our system as an extra. I could also imagine that some manufacturers would release graphics for it.

**Comment by jsenecal** [comment]
We must also consider that Github allows for copyrighted material under [Fair Use](https://www.lumendatabase.org/topics/22), It may not be a problem after all to host them here, on github.

**Comment by m2martin** [comment]
Another option to discuss:
To overcome the need for downloading files from public sources, it may be applicable to create a kind of self-contained import file where the images are included in the YAML for example as base64 string which will be saved to the filesystem in the import step.

**Comment by jbemmel** [comment]
I uploaded front/rear images for Nokia devices to the repo: https://github.com/netbox-community/devicetype-library/pull/1210

Keeping them together with the device definitions makes most sense to me - I checked with our marketing department and got the ok, so uploading them here implies permission to use (within the context of Netbox)

**Comment by danner26** [comment]
All, I have added documentation regarding the front and rear images. All device images must be placed within the manufacturer folder within the `elevation-images` folder in this repo. The manufacturers folder needs to be named exactly the same as the device-types and the module-types folders.

After the manufacturer folder is created, you can then start adding your images. It is required that the file name follows this format:

1. The first part of the name must be a part of the slug which identifies the device, i.e. `7220-IXR-H3`
2. The second part of the file name indicates whether it is a front or rear image, with a dot as the delimiter. This should look like `.front` or `.rear`
3. The final part of the file name is the file type. This can be any of the following types (`'bmp', 'gif', 'pjp', 'jpg', 'pjpeg', 'jpeg', 'jfif', 'png', 'tif', 'tiff', 'webp'`). Of course you need a dot in front of the file type as well, i.e. `.png` or `.jpg`, etc.

PR #1225 resolves this issue
