### ISSUE TITLE
check point 3600 devices have NO LOM interface

### ISSUE THREAD

**Issue by tedserreyn** [netbox-community/devicetype-library#1121]
not even possible.  I am reviewing the guides to see how to modify my checkpoint devices to submit.  We really need to be able to export a full YAML of an existing created device.

**Comment by danner26** [comment]
Please feel free to modify any definitions that you see have this issue, then submit a PR and we would be happy to review the changes

**Comment by danner26** [comment]
@tedserreyn I am not an expert with checkpoints, so please feel free to submit a PR to correct any issues you see. Please also link to the datasheet or supporting documentation if you can. In the meantime I will close this issue. Thank you
