### ISSUE TITLE
Audit Panduit definitions for incorrect child devices

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/devicetype-library#1129]
Seems that a few Panduit device types should actually be modules. For example: https://github.com/netbox-community/devicetype-library/blob/master/device-types/Panduit/FAP12WAGDLCZ.yaml

**Comment by Nealtron** [comment]
I did a little bit of leg work on this since this directly benefits me, but I have no GIT experience so unfortunately I have 2 separate changes in a single PR https://github.com/netbox-community/devicetype-library/pull/1188

**Comment by Nealtron** [comment]
@jeremystretch, my PR was merged. Do you see any more modules that might have been missed?

**Comment by DanSheps** [comment]
Conversely, I actually model these as single devices as I prefer the way they show on a device trace.

I do think that some of those definitions are incorrect as there are acutally 2 MPO12 connectors and 24 LC strands (each strand has a A and a B side)
