### ISSUE TITLE
Support for adding front/back images in device type and support for + sign as in part number

### ISSUE THREAD

**Issue by deku-m** [netbox-community/devicetype-library#113]
HI,

Is it possible to also include in the device types the front/back images of the device?

Also i notice if i use the same name for part number/model the "+" sign isn't allowed.
For some cisco part this is use for example:
C4510R+E / WS-X4748-RJ45V+E

**Comment by ryanmerolle** [comment]
This repo is just to share device types for importing into NetBox.  This repo is a community repo that only follows the NetBox core data model for device types.

The "+" not being valid / allowed is something we would need raised in the main NetBox repo.
