### ISSUE TITLE
Importation tutorial

### ISSUE THREAD

**Issue by kmorin18** [netbox-community/devicetype-library#114]
Hello,

I was wondering if it was possible to document in your readme.md the process for importing this data.

The integrated import feature in netbox only takes text, not full yaml files.

Regards,

**Comment by anlx-sw** [comment]
i just saw your issue while researching another problem. the json/yaml import is only available in the latest versions of netbox - so maybe you need to upgrade.

unfortunately a bulk update of device types is not possible via the gui. is anyone aware of a script to bulk import device types from this repo via cli?

**Comment by rlaneyjr** [comment]
I just happen to need the same thing.  I created a quick script that does the job.  You can get it [here](https://gist.github.com/rlaneyjr/87917f4e9a66d129c392b2353469b34b).

**Comment by rlaneyjr** [comment]
Forgot to mention you will need to: `pip install pynetbox ruamel.yaml`

**Comment by rlaneyjr** [comment]
Also failed to mention, there is a duplicate key error in the yaml file for Arista/DCS-7150SC-64.yaml.  I have created a [pull request](https://github.com/netbox-community/devicetype-library/pull/137).  The build keeps failing for my pull request and I am not sure how to resolve it.

**Comment by ndom91** [comment]
@rlaneyjr thanks for the intial work! For some reason this didnt add any of the interfaces / etc though.

**Comment by rlaneyjr** [comment]
@ndom91 you are correct.  I am working on adding the templates in with pynetbox's API but have yet to succeed.  Thank you for pointing this out.

**Comment by ndom91** [comment]
Ah gotcha, so is that a limitation of pynetbox? Not being able to add interfaces?

**Comment by rlaneyjr** [comment]
@ndom91 no not pynetbox, but netbox itself will not handle nested YAML definitions such as: `{'key': [List of items]}`  I have added the templates after some long hard fighting.  Updated: [GIST](https://gist.github.com/rlaneyjr/87917f4e9a66d129c392b2353469b34b)

**Comment by rlaneyjr** [comment]
> netbox itself will not handle nested YAML definitions such as: `{'key': [List of items]}`
Let me expand on this.  Via the API that is.  I could be wrong.  I did not spend much time TSHOOTing.

**Comment by ndom91** [comment]
Btw, to hide the `urllib3` ssl warnings (if you didnt specify a privatekey), run the following:

```
export PYTHONWARNINGS="ignore:Unverified HTTPS request"
```

**Comment by alagoutte** [comment]
> 
> 
> @ndom91 no not pynetbox, but netbox itself will not handle nested YAML definitions such as: `{'key': [List of items]}` I have added the templates after some long hard fighting. Updated: [GIST](https://gist.github.com/rlaneyjr/87917f4e9a66d129c392b2353469b34b)

Hi,

Thanks for your script, it is not possible to push on this repo ? (can be help some other people...)

**Comment by ndom91** [comment]
@alagoutte the script is not from me, but I did in the meantime find another one that does a great job of dealing with existing manufacturers and devices if there are conflicts, etc. I can highly recommend it:

https://github.com/minitriga/Netbox-Device-Type-Library-Import

**Comment by alagoutte** [comment]
Hi @ndom91, thanks for the link ! i will test ! (may be add on README.md a link for this)
