### ISSUE TITLE
Ethernet33 duplicated in DCS-7280SR2-48YC6

### ISSUE THREAD

**Issue by wmclendon** [netbox-community/devicetype-library#117]
hello,

import error when trying to import YML for DCS-7280SR2-48YC6

issue is due to interface definition "Ethernet33" is listed twice -- there is a Type-o where it should be fixed to "Ethernet43" -- changing that import works fine.

**Comment by wmclendon** [comment]
DCS-7050SX3-48YC12 also has this exact same issue and fix

**Comment by ryanmerolle** [comment]
Fixed in #94 which was just merged.
