### ISSUE TITLE
duplicate model name in device-types/Cisco/WS-C3750G-12S-S.yaml and WS-C3750G-12S-E.yaml

### ISSUE THREAD

**Issue by alextremblay** [netbox-community/devicetype-library#1171]
https://github.com/netbox-community/devicetype-library/blob/bd9fce16f25f0601707dd31faf9430534ddd5da3/device-types/Cisco/WS-C3750G-12S-S.yaml#L3
https://github.com/netbox-community/devicetype-library/blob/bd9fce16f25f0601707dd31faf9430534ddd5da3/device-types/Cisco/WS-C3750G-12S-E.yaml#L3

Both use the same model name as WS-C3750G-12S.yaml

**Comment by danner26** [comment]
Hello @alextremblay, great catch. Do you want to create a PR to fix this?

**Comment by Nealtron** [comment]
Looks like the only difference between those 2 models is the version of firmware they are running. So wouldn't the best option be the removal of duplicate devices? 

https://community.cisco.com/t5/switching/ws-c3750g-12s-e-and-ws-c3750g-12s-s-v04/td-p/2586654
