### ISSUE TITLE
Misleading comment in Ubiquiti ER-X 

### ISSUE THREAD

**Issue by felbinger** [netbox-community/devicetype-library#1173]
https://github.com/netbox-community/devicetype-library/blob/bd9fce16f25f0601707dd31faf9430534ddd5da3/device-types/Ubiquiti/ER-X.yaml#L7

should be something like [store.ui.com/collections/operator-edgemax-routers/products/edgerouter-x](https://store.ui.com/collections/operator-edgemax-routers/products/edgerouter-x)

**Comment by danner26** [comment]
I actually believe this should be the devices datasheet: https://dl.ui.com/datasheets/edgemax/EdgeRouter_X_DS.pdf
