### ISSUE TITLE
Question: How to handle same device type, but different part number

### ISSUE THREAD

**Issue by detvan** [netbox-community/devicetype-library#1265]
Hello,

i understand naming convention in this repository, but how should i handle if vendor has same device type, but different part number.
Typical use case is HPE Edgeline EL1000 Converged Edge System. Please suggest naming convention for yaml files. Thank you very much in advance.

HPE Edgeline EL1000 1GbE 2xRJ45 v3 Pass Thru System
Part Number: 880271-B22

HPE Edgeline EL1000 10GbE 2xSFP+ v2 Pass Thru System
Part Number: 880273-B21

HPE Edgeline EL1000 1GbE 2xRJ45 Pass Thru PXIe System
Part Number: 847555-B21

Similar discussion for reference: #145

**Comment by danner26** [comment]
Hello, sorry for the late response. I was on vacation last week so just starting to catch up. This is one of those cases that makes this really hard to consistently model the data..

I would suggest the file names be as follows:
EdgeLine-EL1000-1GBE2XRJ45-V3.yaml
EdgeLine-EL1000-10GBE2XSFPP-V2.yaml
EdgeLine-EL1000-1GBE2XRJ45-PXIE.yaml

**Comment by detvan** [comment]
thank you
