### ISSUE TITLE
port type change 

### ISSUE THREAD

**Issue by RamSeS-x** [netbox-community/devicetype-library#1422]
hi, 
this model port type wrong. 
please remove poe mode on port 1,2,3 and 4.
port 1-4 using 1000base-x-sfp.
port 5-12 using ethernet 1000base-t.
because 1-4 port using only sfp.
thanks.
https://github.com/netbox-community/devicetype-library/tree/master/device-types/Allied%20Telesis)/IE300-12GP.yamL

---
manufacturer: Allied Telesis
model: IE300-12GP
slug: allied-telesis-ie300-12gp
part_number: AT-IE300-12GP
u_height: 3
is_full_depth: false
console-ports:
  - name: Console
    type: rj-45
power-ports:
  - name: PWR 1
    type: dc-terminal
    maximum_draw: 320
  - name: PWR 2
    type: dc-terminal
    maximum_draw: 320
interfaces:
  - name: port1.0.1
    type: 1000base-x-sfp
  - name: port1.0.2
    type: 1000base-x-sfp
  - name: port1.0.3
    type: 1000base-x-sfp
  - name: port1.0.4
    type: 1000base-x-sfp
  - name: port1.0.5
    type: 1000base-t
    poe_mode: pse
    poe_type: type2-ieee802.3at
  - name: port1.0.6
    type: 1000base-t
    poe_mode: pse
    poe_type: type2-ieee802.3at
  - name: port1.0.7
    type: 1000base-t
    poe_mode: pse
    poe_type: type2-ieee802.3at
  - name: port1.0.8
    type: 1000base-t
    poe_mode: pse
    poe_type: type2-ieee802.3at
  - name: port1.0.9
    type: 1000base-t
    poe_mode: pse
    poe_type: type2-ieee802.3at
  - name: port1.0.10
    type: 1000base-t
    poe_mode: pse
    poe_type: type2-ieee802.3at
  - name: port1.0.11
    type: 1000base-t
    poe_mode: pse
    poe_type: type2-ieee802.3at
  - name: port1.0.12
    type: 1000base-t
    poe_mode: pse
    poe_type: type2-ieee802.3at

```[tasklist]
### Tasks
```

**Comment by danner26** [comment]
Hello, if the type is wrong you are more than welcome to modify the file and submit a PR
