### ISSUE TITLE
nwq device type - FortiSwitch 108F-FPOE

### ISSUE THREAD

**Issue by RamSeS-x** [netbox-community/devicetype-library#1423]
---
manufacturer: Fortinet
model: FortiSwitch 108F-FPOE
slug: fortinet-fs-108f-fpoe
part_number: FS 108F-FPOE
u_height: 1
weight: 5.37
weight_unit: lb
is_full_depth: false
airflow: side-to-rear
console-ports:
  - name: Console
    type: rj-45
power-ports:
  - name: PS1
    type: iec-60320-c14
    maximum_draw: 223
    allocated_draw: 220
  - name: RPScon
    type: dc-terminal
    maximum_draw: 223
    allocated_draw: 220
interfaces:
  - name: port1
    type: 1000base-t
    poe_mode: pse
    poe_type: type2-ieee802.3at
  - name: port2
    type: 1000base-t
    poe_mode: pse
    poe_type: type2-ieee802.3at
  - name: port3
    type: 1000base-t
    poe_mode: pse
    poe_type: type2-ieee802.3at
  - name: port4
    type: 1000base-t
    poe_mode: pse
    poe_type: type2-ieee802.3at
  - name: port5
    type: 1000base-t
    poe_mode: pse
    poe_type: type2-ieee802.3at
  - name: port6
    type: 1000base-t
    poe_mode: pse
    poe_type: type2-ieee802.3at
  - name: port7
    type: 1000base-t
    poe_mode: pse
    poe_type: type2-ieee802.3at
  - name: port8
    type: 1000base-t
    poe_mode: pse
    poe_type: type2-ieee802.3at
  - name: port9
    type: 1000base-x-sfp
  - name: port10
    type: 1000base-x-sfp
  - name: mgmt
    type: 1000base-t
    mgmt_only: true

**Comment by danner26** [comment]
Hello, please feel free to submit a PR with the changes if you would like.
