### ISSUE TITLE
Allow for nested module bays

### ISSUE THREAD

**Issue by dar72** [netbox-community/devicetype-library#1425]
Is it possible to add the functionality to have nested module bays?

We use MPCE Type 2 3D (750-038491) cards in Juniper MX routers, these contain up to two MIC (750-049846) cards to provide the interfaces.

It seems the only way to properly represent this is to have the ability to have the MPCE card as a module to add to the MX router and that MPCE module to also have module bays, then MIC cards can be represented by a module which can be added to the MPCE module which is already part of the MX.

**Comment by dar72** [comment]
Sorry I posted this on the wrong repo

**Comment by danner26** [comment]
No worries, closing this issue then. Thank you.
