### ISSUE TITLE
MikroTik devices with multiple revisions?

### ISSUE THREAD

**Issue by nepeat** [netbox-community/devicetype-library#145]
I would like to contribute my device file for the CCR1036-8G-2S+EM (Rev A/2014?) which differs from the current revision of the CCR1036-8G-2S+EM. How should I name it before shooting it over to the device library? I was thinking about naming it CCR1036-8G-2S+EM (2014) or CCR1036-8G-2S+EM (Rev A) but that certainly would be inaccurate since I do not know what would be a proper way to refer to that model.

Main differences between the original revision and the current revision with the model are
* Only 1 power input
* DB9 Serial instead of rollover RJ45
* Micro USB instead of USB A in front

**Comment by ryanmerolle** [comment]
I think the revision number in the filename and model number makes sense.  Maybe the full name (with year in the name).  I guess my only question would be if you can have a Revision A with different specs across different years.

Regardless, your attention to detail seems good enough.  If these are popular devices that the community thinks you misrepresented in the model number, I'm sure we will get an issue or a PR to adjust.  Other vendors just update the sku / part number for spec changes.

If you cared to model exactly as the manufacturer intended, you can also reach out to them to get their 2 cents.  In some cases, vendors reps have contributed to this repo new devices or device corrections.

I do not have a solid stance given we do not have a precedence like this.  You are the first to bring this issue up.
