### ISSUE TITLE
Test cases fail for interface type: other-wireless

### ISSUE THREAD

**Issue by etherwrangler** [netbox-community/devicetype-library#1460]
In the NetBox web ui there is an interface type of _Other (Wireless)_ available.  If a yaml file is created with the snippet below, the pre-commit script fails because schema/components.json is missing this definition.

```
  - name: wlan2
    type: other-wireless
```
I made sure this is the expected type by exporting a device via the web ui.

**Comment by danner26** [comment]
I just double checked and you are correct, the type `other-wireless` is the correct one. If you'd like, you can create a PR to add this interface type. If you'd rather I can do so as well

Just let me know. Thanks for catching this! As a side note, we try to avoid using other in these definition files as much as possible. 

What interface type are you trying to add that does not already exist?

**Comment by etherwrangler** [comment]
I'm working on adding some Meraki wireless devices.
https://documentation.meraki.com/MR/MR_Overview_and_Specifications/MR46_Datasheet

A dedicated third radio provides real-time WIDS/WIPS, with automated RF optimization.

Since the 3rd radio isn't used for data, Other (Wireless) seemed to fit best.  If you'd prefer that one have another type I can go ahead an update those before I submit the PR that will be coming for that.

I'll get a PR submitted to add other-wireless in a bit.

**Comment by danner26** [comment]
Sounds good about `other-wireless`

Could you send me a link to the datasheet for the device with this radio?

**Comment by etherwrangler** [comment]
https://documentation.meraki.com/MR/MR_Overview_and_Specifications/MR46_Datasheet
