### ISSUE TITLE
Noob Question: how to work on multiple device_types simultaneously 

### ISSUE THREAD

**Issue by constantpinger** [netbox-community/devicetype-library#149]
This might be a github question.

If I have a pull request in progress for device types in a series of manufacturer. 

I then start to work on new device types for another manufacturer. If I commit from the original fork these then confuse the pull request.

What is the best way to work on more than one set of device_types at the same time (or more likely the next set whilst waiting in the queue for the pull request to complete)?

**Comment by constantpinger** [comment]
Is the answer to create a branch in my own fork, and create separate pull requests from each branch?

**Comment by ryanmerolle** [comment]
Yes.  Branches will allow you to separate work between each PR.
