### ISSUE TITLE
Raritan PX3 devices can come with different PDU controllers

### ISSUE THREAD

**Issue by kaechele** [netbox-community/devicetype-library#1556]
There is the original controller, mentioned in Raritan documentation as simply **PX3** and then there is the **PX3 with iX7**, which is a newer, more advanced controller.
Currently, only the PX3-5138JR model is modelled as PX3. All others are modelled as PX3 with iX7. However, like all other PX3 models, the PX3-5138JR is shipped as PX3 with iX7 these days.
Unfortunately, there is no way of telling from the model number whether the device comes with the original controller or an iX7 (i.e. there is no revision code printed on the label, at least for our models). The original controller is built into devices shipped prior to 2018 (the iX7 was released in 2017).

From a modelling perspective the difference is mainly:
| | PX3 | PX3 with iX7 |
|----|-------|-------------------|
| Serial | DE-9 | RJ-45 |
| Ethernet 1 | 100Base-TX | 1000Base-T |
| Ethernet 2 | N/A | 100Base-TX |

In Raritan's ZeroU PDUs (Model Number ending in V) this element is replaceable, so could technically be modelled as a module.

I'm unsure how to handle this.

Documentation reference: https://d3b2us605ptvk2.cloudfront.net/download/px3/version-3.4.10/PX3_PX2_QSG_1C_3.4.0.pdf

**Comment by danner26** [comment]
Maybe I am missing something here, it looks like there are 3 listed. `PX2`, `PX3` and `PX3-iX7`
The product names are the difference, so there should be 3 devicetypes modelled

**Comment by kaechele** [comment]
Thanks for the reply. Unfortunately, even though the guide lists 3 different models the model numbers for sale don't seem to differ between the PX3 variants. A PX3-5464V sold in 2018 will be a PX3-iX7 variant. Our 2015 PX3-5464V are PX3 (non iX7 models). It's a bit of a mess.

Not sure if we should work to establish some kind of guidelines for this repository around cases like this.

**Comment by danner26** [comment]
So it sounds like there are older hardware revisions, which are the `PX3-5464V` and `PX3-5464V` you listed. I have a question, when you look at the devices configuration/cli output, does it say it is a `PX3-5464V` or a `PX3`?

**Comment by kaechele** [comment]
After some more research I conclude that these devices are a hot mess when it comes to revisions.

The documentation is  inconsistent between versions in how it refers to devices. I have come to the conclusion that you cannot tell which PX3-5464V (or really any of the PX3 devices) you are dealing with until you look at the unit's controller.

But to answer your question: Awkwardly, our device in its initial state had a hostname of `PX2`. It was made in 2015.

Here's what I found so far:
- The iX7 makes its debut in [version 3.3.10 of the user guide](https://d3b2us605ptvk2.cloudfront.net/download/px3/version-3.3.10/PX3-345000Series-v3.3.10-UserGuide.pdf). This user guide has a somewhat useful comparison of the different generations of devices on pages xviii (PDF page 18) and following.
 - All mentions of the older generation PX3s is removed from documentation starting with version 4 of the firmware.
 - There are even sub-variants of the iX7 controller which differ in port configuration:
   > Note: ETH1-10/100/1000 (marked in green) supports up to 1000 Mbps. ETH2-10/100 (marked in
white) supports up to 100 Mbps. There are single and dual ethernet varieties of the iX7 controller,
and that port speed is labeled.

   from: [Raritan PX-Series PDU User Guide v4.0.20, page 81](https://cdn1.raritan.com/download/pdu-g2/4.0.41/PDU_G2_UG_A2_4.0.20.pdf)

So I don't think you can generalize devicetypes across these revisions like we do in this repository.

Is there any guidance on what should be done in these cases? If not, is it worth it do define such and document them for the sake of consistency?

**Comment by danner26** [comment]
Geez, there are a handful of manufacturers that have crappy formats like this.. If I am reading this correctly, these devices slot into a chassis? Is that the case?
