### ISSUE TITLE
jsonschema.RefResolver is deprecated in favor of the https://github.com/python-jsonschema/referencing library

### ISSUE THREAD

**Issue by abhi1693** [netbox-community/devicetype-library#1580]
DeprecationWarning: jsonschema.RefResolver is deprecated as of v4.18.0, in favor of the https://github.com/python-jsonschema/referencing library, which provides more compliant referencing behavior as well as more flexible APIs for customization. A future release will remove RefResolver.

**Comment by danner26** [comment]
Hey @abhi1693 I noticed that as well. I started poking around with migrating it but I have not utilized this much before. If you are able to migrate it, please feel free! Otherwise I will keep looking at it when I have time

**Comment by abhi1693** [comment]
Actually both libraries are new to me so I'm not sure how soon I'll be able to get the code ported.

**Comment by danner26** [comment]
No worries, we can tackle it as we get time
