### ISSUE TITLE
Suggestion: add .pickle files to .gitignore

### ISSUE THREAD

**Issue by jbemmel** [netbox-community/devicetype-library#1661]
There is a CI check that fails when a commit includes test/*.pickle files by accident

Perhaps those could be added to .gitignore?

**Comment by danner26** [comment]
These files should not be ignored by git, they do need to be git previsioned. That being said, they should not be added in PRs/commits.. It is a Friday so I am a bit fried but if you have a way to fix this issue, or any ideas, I would very much appreciate it!
