### ISSUE TITLE
Adding APC AP8653 to devices-type

### ISSUE THREAD

**Issue by pierrickj** [netbox-community/devicetype-library#1694]
Hello,

I'd like to submit an .yaml device-type file for APC AP8653 PDU that doesn't exist in this repo yet.

This page told to open an issue first : https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md

(my first time here).

What are next steps ? 

Thanks for your help

**Comment by bberberov** [comment]
This repo has its own [`CONTRIBUTING.md`](https://github.com/netbox-community/devicetype-library/blob/master/CONTRIBUTING.md) file.  That's the one I followed.

**Comment by danner26** [comment]
You are welcome to submit a PR to this repository at any time! Pond doing so. I or one of the other maintainers will review it if all of checks pass. Thanks for your contributions!

**Comment by pierrickj** [comment]
Hello,

Thanks for your answer, how can i troubleshoot this unsuccessful test ?

![image](https://github.com/netbox-community/devicetype-library/assets/114187002/e1d6c6a5-8dd3-4054-a9ce-05e5697b795f)

**Comment by bberberov** [comment]
You need to set up the [pre-commit checks](https://github.com/netbox-community/devicetype-library#data-validation--commit-quality-checks) locally, and run them against your commit.  When I did it, I could see which "files were modified".
