### ISSUE TITLE
`description` in device and module types

### ISSUE THREAD

**Issue by bberberov** [netbox-community/devicetype-library#1715]
I've noticed that the current schema used for commit and PR validation does not include the `description` field.  `.yaml` types I wrote and imported into a NetBox v3.6.1 did not fail to import, and properly set the `description` field.  Should the schema be updated, or is there something else I'm not understanding?

**Comment by danner26** [comment]
Sorry, what is the question here? You should be able to use `description` and we can add test cases. Just mention it in your PR. Thank you
