### ISSUE TITLE
Add AVM Fritz!Box 7590 AX

### ISSUE THREAD

**Issue by tschmidtb51** [netbox-community/devicetype-library#1719]
I would like to add AVM Fritz!Box 7590 AX to the device list. However, I came across the issue that there are (at least) 4 version of it (see different article numbers):
- 20002999 (international; https://en.avm.de/products/fritzbox/fritzbox-7590-ax/technical-specifications/)
- 20002998 (DE; without ISDN: https://avm.de/produkte/fritzbox/fritzbox-7590-ax/technische-daten/)
- 20002929 (DE; with ISDN: https://avm.de/produkte/fritzbox/fritzbox-7590-ax/technische-daten/)
- 20003022 (A/CH; https://at.avm.de/produkte/fritzbox/fritzbox-7590-ax/technische-daten/)

How should the `model` and `slug` be set?

**Comment by danner26** [comment]
This is a community driven repo. If you would like to see a device added I suggest you take a look at existing files, and try to create your own for this device. After doing so feel free to submit a PR and we will review it/help you fix it up before merging!
