### ISSUE TITLE
Default console port configuration in `comments`

### ISSUE THREAD

**Issue by bberberov** [netbox-community/devicetype-library#1722]
Currently we keep this information separately, but what about including the default console port configuration for switches, etc., in the `comments` field, with Markdown?  Something like this:

|Parameter   |Setting|
|------------|-------|
|Baud Rate   |  9600 |
|Parity      |    No |
|Data Bits   | 	   8 |
|Stop Bits   |     1 |
|Flow control|  None |

**Comment by danner26** [comment]
I wouldn't be against this
