### ISSUE TITLE
Juniper EX2300-C-12P import failure

### ISSUE THREAD

**Issue by 2bithacker** [netbox-community/devicetype-library#173]
Tried to import the Juniper EX2300-C-12P template, but got the following error:

> console-ports[1] __all__: Console port template with this Device type and Name already exists.

It appears to be due to the USB and serial console ports having the same name.

NetBox v2.8.7

**Comment by ryanmerolle** [comment]
That is exactly the problem.  Do you want to submit a PR to fix this?  Maybe console_usb?

**Comment by 2bithacker** [comment]
Sure. Going to take a look at adding a test for this sort of thing, too.

**Comment by ryanmerolle** [comment]
Thanks @2bithacker 

If you did not look to setup a test, I was.  The pytest / jsonschema setup is pretty simple to add this sort of check to.

**Comment by 2bithacker** [comment]
Looks like jsonschema can't do this yet, based on json-schema-org/json-schema-vocabularies#22.
