### ISSUE TITLE
Some missing Cisco devices

### ISSUE THREAD

**Issue by gormur** [netbox-community/devicetype-library#1736]
The following Cisco devices seems to be missing:

Catalyst 2960L-48PS-LL
Catalyst 2960L-8TS-LL
Catalyst 2960S-48LPS-L
Catalyst 3560CS-8PC-S
Catalyst 3560CX-8PC-S
Catalyst 3560CX-8TC-S
Catalyst 3650-48TQ-S

**Comment by danner26** [comment]
This is a community driven repo. If you would like to see a device added I suggest you take a look at existing files, and try to create your own for this device. After doing so feel free to submit a PR and we will review it/help you fix it up before merging!
