### ISSUE TITLE
Suggestion: Add DECT

### ISSUE THREAD

**Issue by tschmidtb51** [netbox-community/devicetype-library#1928]
Currently, we can't specify that a device has a DECT interface. However, that is interesting to us, especially from a threat perspective. Therefore, I suggest to add an interface type `dect`.

I'm happy to provide a PR for that if it helps.

**Comment by DanSheps** [comment]
> Currently, we can't specify that a device has a DECT interface. However, that is interesting to us, especially from a threat perspective. Therefore, I suggest to add an interface type `dect`.

This needs to be suggested in the main nentbox repository, however I can tell you that this will likely be rejected.

**Comment by netravnen** [comment]
> Currently, we can't specify that a device has a DECT interface. However, that is interesting to us, especially from a threat perspective. Therefore, I suggest to add an interface type `dect`.

Your use case cannot be satisfied using custom fields?
