### ISSUE TITLE
Arista Yaml syntax issues?

### ISSUE THREAD

**Issue by modonovan** [netbox-community/devicetype-library#1933]
Hi all, 

Firstly, *superb* work on this project, it's a fantastic resource and one that has been massively helpful to us.

I've just tried a restricted / slugs based import of some Arista switches into our Netbox development instance and I'm running around with an issue.

The error in question is:

```
Manufacturer Exists: Arista - 5
{"front_image":["The submitted data was not a file. Check the encoding type on the form."],"rear_image":["The submitted data was not a file. Check the encoding type on the form."]}
Traceback (most recent call last):
  File "/app/./nb-dt-import.py", line 853, in <module>
    main()
  File "/app/./nb-dt-import.py", line 826, in main
    createDeviceTypes(deviceTypes, nb)
  File "/app/./nb-dt-import.py", line 680, in createDeviceTypes
    dt.id, nb)
UnboundLocalError: local variable 'dt' referenced before assignment
```

I get this when using the following `SLUGS` as a feed:

`SLUGS="arista-dcs-7280qra-c36s-f arista-dcs-7280tr-48c6-f arista-dcs-7050sx-64-f arista-dcs-7050tx-48 arista-dcs-7050tx-72q"`

And when doing a vendor specific import run using:

`./nb-dt-import.py --vendors arista`

This when trying to import the devices in question into **Netbox version v3.7.2**

Any ideas?

Seems the `rear_image` key isn't present or understood by Netbox maybe?

**Comment by netravnen** [comment]
@modonovan can you provide en example yaml config of the device producing the import error?

**Comment by danner26** [comment]
Hey, so this is spawning from the [Device-Type-Library-Import](https://github.com/netbox-community/Device-Type-Library-Import)

@netravnen based on the slug they are trying to import:

- [arista-dcs-7280qra-c36s-f](https://github.com/netbox-community/devicetype-library/blob/63cb7ede1f5fba45ff6f08406d90955240b0e1d4/device-types/Arista/DCS-7280QRA-C36S-F.yaml)
- [arista-dcs-7280tr-48c6-f](https://github.com/netbox-community/devicetype-library/blob/63cb7ede1f5fba45ff6f08406d90955240b0e1d4/device-types/Arista/DCS-7280TR-48C6-F.yaml)
- [arista-dcs-7050sx-64-f](https://github.com/netbox-community/devicetype-library/blob/63cb7ede1f5fba45ff6f08406d90955240b0e1d4/device-types/Arista/DCS-7050SX-64-F.yaml)
- [arista-dcs-7050tx-48](https://github.com/netbox-community/devicetype-library/blob/63cb7ede1f5fba45ff6f08406d90955240b0e1d4/device-types/Arista/DCS-7050TX-48.yaml)
- [arista-dcs-7050tx-72q](https://github.com/netbox-community/devicetype-library/blob/63cb7ede1f5fba45ff6f08406d90955240b0e1d4/device-types/Arista/DCS-7050TX-72Q.yaml)


@modonovan can you try just importing arista-dcs-7050tx-72q and let me know if it works?

**Comment by netravnen** [comment]
I can confirm on Netbox 3.7.4 and using the importer script works on my end.

```
netbox# git -C /opt/Device-Type-Library-Import/repo log -n 1 --oneline
dd0d92f1 (HEAD -> master, upstream/master, origin/master) Regenerate master slug list after successful PR merge
```

```
netbox# git -C /opt/Device-Type-Library-Import log -n 1 --oneline 
136344d (HEAD -> master, tag: v2.0.2-2023-08-01, origin/master) Release v2.0.2 (#102)
```

Maybe try updating the repo? And retry the import script... 🤔 💭 

```
$ git -C /app/repo pull origin master:master
```

**Comment by danner26** [comment]
Thanks for checking @netravnen 
@modonovan were you able to resolve this? Or are you still experiencing it?

**Comment by modonovan** [comment]
Belatedly confirming (sorry about the delay responding) that, I'm able to import using `--vendor=Arista` and `--slugs=SLUGS=arista-dcs-7050tx-72q arista-dcs-7280qra-c36s-f arista-dcs-7280tr-48c6-f arista-dcs-7050sx-64-f arista-dcs-7050tx-48 arista-dcs-7050tx-72q` on Netbox v3.7.3 without issue now. 

I'm happy to close this issue.
