### ISSUE TITLE
Cisco ASR9910 devices bays should be modeled as module bays

### ISSUE THREAD

**Issue by wgibbons21** [netbox-community/devicetype-library#1969]
https://github.com/netbox-community/devicetype-library/blob/4123d2aaa2f4319d50327b4b39129bc0c6cf7b12/device-types/Cisco/ASR-9910.yaml#L47-L67

Cisco ASR9910 devices bays should be modeled as module bays

**Comment by DanSheps** [comment]
You are free to open a PR
