### ISSUE TITLE
Duplicate key error when importing from current master via docker container

### ISSUE THREAD

**Issue by KPTheProf** [netbox-community/devicetype-library#1970]
{"error": "duplicate key value violates unique constraint \"dcim_manufacturer_slug_key\"\nDETAIL:  Key (slug)=(watchguard) already exists.", "exception": "IntegrityError", "netbox_version": "3.7.3", "python_version": "3.11.4"}

**Comment by netravnen** [comment]
@KPTheProf Can this be closed?

**Comment by KPTheProf** [comment]
Hi @netravnen, I haven't done an import recently, but if you think that this has fixed the issue, then please close.

**Comment by danner26** [comment]
The PR has resolved it. I am closing this based on that
