### ISSUE TITLE
PA-3250.yaml - device speed wrong for ethernet1/13-1/16

### ISSUE THREAD

**Issue by antoinekh** [netbox-community/devicetype-library#2091]
Documentation palo:
https://docs.paloaltonetworks.com/hardware/pa-3200-hardware-reference/pa-3220-series-overview/front-panel-3200-series

> PA-3250 and PA-3260 firewalls
—Ports 13 through 20 are SFP (1Gbps) or SFP+ (10Gbps) based on the installed transceiver.

But on the file:
https://github.com/netbox-community/devicetype-library/blob/master/device-types/Palo%20Alto/PA-3250.yaml

![image](https://github.com/netbox-community/devicetype-library/assets/52744345/4f0d296f-f369-4100-aec1-61810cca4c0b)

**Comment by robinreinhardt** [comment]
fixed in PR #2122

**Comment by danner26** [comment]
This has been merged
