### ISSUE TITLE
Front and Rear images

### ISSUE THREAD

**Issue by aletessier** [netbox-community/devicetype-library#212]
Are there any plans on supporting front and rear images for the device types in this library ?

**Comment by catSIXe** [comment]
![image](https://user-images.githubusercontent.com/63829136/95264586-e1d12f80-082f-11eb-8f52-3ad100d23c7d.png)
I have made one for the TL-SG1024D, would be great to have it integrated here too

**Comment by ryanmerolle** [comment]
We could probably link to them, but I do not think we should take images of devices and embed them in the repo.  That could open up concerns with the the manufacturers.  I would want to get other opinions here especially from other maintainers.

**Comment by DanSheps** [comment]
There is currently a FR to add a base64 encode/decode to the YAML.  I think once that is done there wouldn't be any objections to device images.

**Comment by Abulhallaj** [comment]
I made a repo for my use here: https://github.com/Abulhallaj/netbox-deviceimage
