### ISSUE TITLE
Wrong interface names for Fortigate 40F

### ISSUE THREAD

**Issue by vinceneil666** [netbox-community/devicetype-library#2123]
WAN-1 should be WAN
internal1 should be lan1
internal2 should be lan2
internal3 should be lan3

In file:   device-types/Fortinet/FG-40F.yaml

I cant seem to find any documentation links for this. But looking at the 40F in front of me, I can see that it is so.

**Comment by danner26** [comment]
Please feel free to make a PR to resolve this, thank you.
