### ISSUE TITLE
Is there a way to support multiple OS variation for the same device?

### ISSUE THREAD

**Issue by skg-net** [netbox-community/devicetype-library#213]
Is there a way to support multiple OS variation for the same device? Most of the WhiteBox / Bright Box supports different OS.
For example: Dell Devices support various NOSes (OS10, SONiC, Cumulus etc) each have a different interface naming convention. Is there a way to accommodate it? or Create 1 Yaml Per Device Per OS? I prefer extending the Interface section with the additional NOS key.

**Comment by ryanmerolle** [comment]
Sorry for the delayed response.  I think this should work under the current model.  Platform is linked to a device only when created.  We do not currently link a platform to a device type.

So if you deploy SONiC with a device, you can set that platform at creation.  You can also change the platform at any time for said device.
