### ISSUE TITLE
Fortigate interfaces (Fortilink)

### ISSUE THREAD

**Issue by vinceneil666** [netbox-community/devicetype-library#2151]
All Fortigates come with a predefined aggregate interface called 'Fortilink', default one or two physical interfaces are members of this aggregated (depending on the model)

Would it be a smart thing to include this 'fortilink' interface in the different devices ? I woul think that the information of what interface is member - really is not important since it can and probably will be moved around.

I am doing some automation between netbox and fortimanager - and for provisioning of vlan interfaces - I do need to have that interface defined, as of now I just add it manually.

**Comment by danner26** [comment]
Hello, currently we are only modelling physical interfaces in the devicetype-library, but you are welcome to fork this repo and make the changes on your forked repo. Then you can model this information. Hopefully this helps.
