### ISSUE TITLE
Best way to keep track of SuperMicro 45 bay Jbod

### ISSUE THREAD

**Issue by 07stuntar1** [netbox-community/devicetype-library#225]
Hi can someone give advice or best way to add a Supermicro Server and JBOD to netbox? 

I am using Freenas and I am trying to figure out the best way to organize and keep track of the hard drives gptid and serial numbers per each hard drive slot.

SuperMicro [SuperServer 6029U-TRTP](supermicro.com/products/system/2U/6029/SYS-6029U-TRTP.cfm)
connects to the super chassis via External SAS expander
SuperChassis [847DE1C-R2K04JBOD](https://www.supermicro.com/en/products/chassis/4U/847/SC847DE1C-R2K04JBOD)

Or does someone have a template I can upload of the jbod?

**Comment by danner26** [comment]
Do you still need assistance with this? @07stuntar1
