### ISSUE TITLE
Pull request workflow awaiting approval

### ISSUE THREAD

**Issue by tdilldine** [netbox-community/devicetype-library#2257]
I submitted a pull request #2254 and it has not gone through the checks as the workflow shows it is awaiting approval even though pull requests submitted after have gone through the process. This is the second time I have submitted the pull request (it had the same thing happen the first time) as I realized the yaml file needed to be edited slightly and then re-submitted. This is my first time using GitHub so I'm not familiar with the process, just wanting to make sure I didn't mess anything up.

**Comment by tdilldine** [comment]
Given that I am a first time contributor, I'm guess this is coming into play: "By default, all first-time contributors require approval to run workflows." So I just wasn't sure how long the turn around time for that approval usually is.

**Comment by DanSheps** [comment]
I have approved it.
