### ISSUE TITLE
How to handle Master/Link PDUs

### ISSUE THREAD

**Issue by benclement** [netbox-community/devicetype-library#233]
What is the best way to handle Master / Link PDUs in the devicetype-library and Netbox? I have a number of Servertech PDUs such as model STV-4101C (master) / SEV-4101C (Link). In my netbox deployment I've created a single YAML (attached as PDF for reference) that have both Master and Link power outlets but wondering if there is there a way to create individual device types for the master and link part numbers and then somehow "link" them in Netbox so they appear logically as a single device as they do for mgmt? 

Let me know if this is a question better asked in https://github.com/netbox-community/netbox and I'll post there. 

Thanks 

[STV-4101C.pdf](https://github.com/netbox-community/devicetype-library/files/5283777/STV-4101C.pdf)

**Comment by antonalekseev** [comment]
If _link_ PDU can be considered as a child device of a _master_ PDU, [device bays](https://netbox.readthedocs.io/en/stable/core-functionality/devices/#device-bays) can be used to conceptually model such a setup.

**Comment by ryanmerolle** [comment]
@antonalekseev presents a option, but I think that would be confusing since devices bays signify items within a device.  This model, at first thought, sounds like a model similar to stack switches and virtual chassis.  That is just me thinking outloud, and not testing against that model or even seeing it makes sense.

**Comment by ryanmerolle** [comment]
Thinking about this further, maybe virtual chassis make sense for this model?  Not sure.
