### ISSUE TITLE
typo in Arista DCS-7130-48LS-R.yaml

### ISSUE THREAD

**Issue by amylieb** [netbox-community/devicetype-library#2346]
`device-types/Arista/DCS-7130-48LS-R.yaml` has `model` and `part_number` definitions `DCS-7130-48LS-F` instead of `DCS-7130-48LS-R`.

Note that this breaks the [Device Type Library Import](https://github.com/netbox-community/Device-Type-Library-Import) for Arista since there's also a `device-types/Arista/DCS-7130-48LS-F.yaml` with the same model definition.

**Comment by jonkerj** [comment]
Hi, I was adding a couple of devices, and came across your issue. Too bad nobody replied, but I fixed it in PR #2369, so if that gets merged, you should be golden.
