### ISSUE TITLE
Arista CCS-720XP-96ZC2 QSFP Interfaces are incorrect

### ISSUE THREAD

**Issue by LotusNotes4Lyfe** [netbox-community/devicetype-library#2370]
The QSFP28 100 gig interfaces on the CCS-720XP-96ZC2 are 97/1 and 98/1, not 100/1 and 101/1. 
100 and 101 are SFP28 25 gig interfaces.

**Comment by harryajc** [comment]
Create a pull request of these changes and we will review it.
