### ISSUE TITLE
InsecureRequestWarning: Unverified HTTPS request

### ISSUE THREAD

**Issue by marmalodak** [netbox-community/devicetype-library#2373]
I followed the Netbox installation instructions closely. Specifically, these steps for installing a certificate: https://netboxlabs.com/docs/netbox/en/stable/installation/5-http-server/

When I run `./nb-dt-import.py` as the instructions say, I still see a bunch of these messages:

`/home/john/device-type-import/Device-Type-Library-Import/venv/lib/python3.10/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'something.something.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings`

Do I need a separate certificate for devicetype-library?

**Comment by danner26** [comment]
Hello, this belongs in the Device-Type-Library-Import repo. Please move it over there if you still need help
