### ISSUE TITLE
Update the test cases to disallow non-standard characters 

### ISSUE THREAD

**Issue by harryajc** [netbox-community/devicetype-library#2418]
Update the test cases to disallow non-standard characters in device or module file names.

Following are a list of characters that are not allowed in file names in windows and Linux

`< (less than)`
` > (greater than)`
` : (colon - sometimes works, but is actually NTFS Alternate Data Streams)`
` " (double quote)`
` / (forward slash)`
` \ (backslash)`
` | (vertical bar or pipe)`
` ? (question mark)`
` * (asterisk)`

**Comment by danner26** [comment]
This has been implemented
