### ISSUE TITLE
How to test yaml files before you submit it 

### ISSUE THREAD

**Issue by jawyoonis** [netbox-community/devicetype-library#246]
Hey guys, I am new to netbox and i work for dell emc. I created some new device types but i am trying to figure out how to test the yaml files before i submit PR.

@ryanmerolle @jeremystretch

**Comment by antonalekseev** [comment]
You should clone the repository, create virtualenv, activate it, install dependencies `pip install -r requirements.txt` and then run tests with `pytest --tb=line -v`. Those steps are from CI validation process which triggers on every PR, see https://github.com/netbox-community/devicetype-library/blob/c68017c9afbb2d539e9a7f58d57f1bb6d493a753/.github/workflows/validation.yml#L19-L22.

**Comment by DanSheps** [comment]
You can also submit a draft PR to have the tests run
