### ISSUE TITLE
Update the test cases to prevent non-ascii characters in yaml files

### ISSUE THREAD

**Issue by ravench** [netbox-community/devicetype-library#2461]
NetBox appears to not be able to handle non-ascii characters.
This causes issues when importing devices or modules that contain non-ascii characters.
Those are usually dashes (long, short, ect) and symbols like (r) or (tm).

In a shell, the files at issue can be found using `grep`: 

```shell
LC_ALL=C  grep -l "[\x80-\xFF]" ./**/*.yaml 
```

There should be a test for this. There seems to be no applicable test in `pre-commit-hooks` and no flag for `yamlfmt` or `yamllint`, so handling this in a own hook or in pytest seems to be necessary.

Unfortunately, I don't understand pytest well enough to write my own tests, therefore this is an issue and not a pull request.

**Comment by grische** [comment]
@ravench all Netbox instances I have access to do handle non-ASCII characters fine, e.g. in label fields. See #3813
