### ISSUE TITLE
MX7000 redaction

### ISSUE THREAD

**Issue by zeridon** [netbox-community/devicetype-library#2473]
Dell MX7000 chassis seems modeled wrong (https://github.com/netbox-community/devicetype-library/blob/master/device-types/Dell/PowerEdge-MX7000.yaml)

The chassis has 8 device bays (front) for blades.

And 6 back IO modules (IOM) for fabric cards.

**Comment by harryajc** [comment]
Yes your right, the `power-ports` should also be modeled as `module-bays` as they are hot swappable.

Create a PR with these changes and we will review it. There is a guide [here[(https://github.com/netbox-community/devicetype-library/blob/master/CONTRIBUTING.md)
