### ISSUE TITLE
Implement github page for easy browsing

### ISSUE THREAD

**Issue by tb-killa** [netbox-community/devicetype-library#29]
To use the full power of this repo, a github page should be generated from this repo via Travis.
This page is primarily used to get a direct overview of the already available devices, but also to get the data from netbox itself or other third party application via json request or similar and to process it dynamically.

**Comment by jeremystretch** [comment]
Why would an external static page be necessary? The repo is already broweable on GitHub, and [raw files](https://raw.githubusercontent.com/netbox-community/devicetype-library/master/device-types/Juniper/EX4300-48P.yaml) can be retrieved directly to enable automated import to NetBox.
