### ISSUE TITLE
duplicate file names under Ubiquiti

### ISSUE THREAD

**Issue by kkido** [netbox-community/devicetype-library#331]
There are duplicate file names with lower/upper case under Ubiquiti
- US-16-150W.yaml and us-16-150w.yaml
- US-24-500W.yaml and us-24-500w.yaml

**Comment by kkido** [comment]
when case insensitive system pulls the repo, it will not see those files as a different file and collapse them into one file. US-16-150W.yaml/us-16-150w.yaml and US-24-500W.yaml/us-24-500w.yaml seem to be same device but the file content is slightly different. One of them should be deleted if it's a same device

**Comment by VitMain** [comment]
git clone https://github.com/netbox-community/devicetype-library.git
Cloning into 'devicetype-library'...
remote: Enumerating objects: 58, done.
remote: Counting objects: 100% (58/58), done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 4318 (delta 13), reused 10 (delta 0), pack-reused 4260
Receiving objects: 100% (4318/4318), 709.05 KiB | 3.90 MiB/s, done.
Resolving deltas: 100% (3312/3312), done.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'device-types/Ubiquiti/US-16-150W.yaml'
  'device-types/Ubiquiti/us-16-150w.yaml'
  'device-types/Ubiquiti/US-24-500W.yaml'
  'device-types/Ubiquiti/us-24-500w.yaml'
