### ISSUE TITLE
Cisco ASR920 Router

### ISSUE THREAD

**Issue by eN0Rm** [netbox-community/devicetype-library#344]
Can't find Cisco ASR920 router. Do I overlook it or should I create a PR?

**Comment by eN0Rm** [comment]
https://www.cisco.com/c/en/us/support/routers/asr-920-series-aggregation-services-router/series.html


ASR 920-4SZ-A Router
Status: Available | Release Date: 31-Jul-2014

ASR 920-4SZ-D Router
Status: Available | Release Date: 29-Jul-2015

ASR 920-8S4Z-PD Router
Status: Available | Release Date: 03-Oct-2019

ASR 920-10SZ-PD Router
Status: Available | Release Date: 31-Oct-2014

ASR 920-12CZ-A Router
Status: Available | Release Date: 31-Jul-2014

ASR 920-12CZ-D Router
Status: Available | Release Date: 31-Jul-2014

ASR 920-12SZ-IM Router
Status: Available | Release Date: 29-Jul-2015

ASR 920-24SZ-IM Router
Status: Available | Release Date: 29-Jul-2015

 
ASR 920-24SZ-M Router
Status: Available | Release Date: 30-Nov-2014

ASR 920-24TZ-M Router
Status: Available | Release Date: 30-Nov-2014

ASR 920U-12SZ-IM Router
Status: Available | Release Date: 30-May-2017

ASR-920-12SZ-A Router
Status: Available | Release Date: 13-Aug-2018

ASR-920-12SZ-D Router
Status: Available | Release Date: 13-Aug-2018

ASR-920-12SZ-IM-CC Router
Status: Available | Release Date: 08-Jun-2018

ASR-920-20SZ-M Router
Status: Available | Release Date: 28-Aug-2018

**Comment by ryanmerolle** [comment]
You do not have to ask for permission on starting a PR.  If you so not see the model(a) then it is not in the repo.

You are welcome to submit a PR.
