### ISSUE TITLE
Modeling the Dell FX2s Chassis

### ISSUE THREAD

**Issue by mddeff** [netbox-community/devicetype-library#352]
Was going to model up the Dell FX2 Chassis, wanted to get people's input.  I'm just going the model the 4bay version as its the most common I've seen, if somebody wants the [2, 3, 6, or 8 bay](https://www.dell.com/support/manuals/en-us/poweredge-fx2/fx2ownersmanual/sled-slot-numbering?guid=guid-83cda9e7-18c6-4722-b147-e94daabd5ac5&lang=en-us), I'm happy to do those as well.

Like the Dell M1000e Blade Center Chassis, it has bays on the back for networking modules.  

Some are just [direct passthrough](https://www.dell.com/support/manuals/en-us/poweredge-fx2/fx2ownersmanual/io-module-port-mapping%E2%80%94four-bay-chassis?guid=guid-a2b88bfb-faca-46d2-8e1d-c618c32cf672&lang=en-us
) to the network cards *on* the sled servers ("blades") that get plugged in the front.  I think Front/Rear ports would be the best way to model this.  This is helpful for tracing the mapping of the rear ports to which actual ethernet interfaces on which sled (a constant problem if you dont have the linked diagram taped to your rack...)

Unfortunately you can also get Network Switches which are intelligent layer 2/3 devices, and would (imo) be better suited for the parent/child device model given they are their own autonomous devices that have their own control planes.  Additionally tracking the network interfaces between the sleds and the switching network module allow for better granularity in config management when using Netbox as a source for automatic configuration.  But I could be convinced otherwise.

And to complicate maters, the network switch modules dont always have the same number of ports. So just statically setting them on the FX2 chassis device type seems clumsy.

As I'm writing this, I think a Parent/child is good for both, and an additional device type can just be of type patch panel (With front/rear ports).

Thoughts welcome.

**Comment by roperodwayfree** [comment]
For modeling the Dell PowerEdge M1000e chassis I added the M1000e as a parent device. For the childs, first I created the device types as parents, then I created the devices (adding the bays slots to the device not the device type) and then after creating all the devices I changed the device type to be a child and it let me add my blades to the M1000e but it let me use the bays. I currently testing if everything is working properly.

**Comment by kmorin18** [comment]
How did you guys configure the passthrough ports to associate a port on the chassis to an interface on a blade?

**Comment by T3chie-404** [comment]
Was the FX2s ever added to a public release I can use?

**Comment by aaronaxvig** [comment]
I think the best practice has changed in the 5 years since the Inventory recommendation was made.  It would now be best to model this type of chassis as a parent device (the chassis) with device bays which devices (the nodes) are installed into.  I added some Cohesity hardware yesterday that is like this.  Planning to do some other ones this week.

https://netboxlabs.com/docs/netbox/models/dcim/devicebay/

> For example, a 2U parent chassis might house four individual blade servers. The chassis would appear in the rack elevation as a 2U device with four device bays, and each server within it would be defined as a 0U device installed in one of the device bays.
