### ISSUE TITLE
Modules for Cisco Catalyst 4506-E

### ISSUE THREAD

**Issue by AShelpyakov** [netbox-community/devicetype-library#353]
In this repo we have "Catalyst 6506-E". What is the best way add to this chassis these front modules:
Mod Ports Card Type                              Model             
---+-----+--------------------------------------+------------------
 1     4  Sup 7-E 10GE (SFP+), 1000BaseX (SFP)   WS-X45-SUP7-E     
 2    12  1000BaseX SFP                                   WS-X4712-SFP-E    
 3    48  10/100/1000BaseT EEE (RJ45)            WS-X4748-RJ45-E   
 4    48  10/100/1000BaseT EEE (RJ45)            WS-X4748-RJ45-E   
 5    48  10/100/1000BaseT EEE (RJ45)            WS-X4748-RJ45-E   
 
Should I create new templates for modules?

**Comment by ryanmerolle** [comment]
We have not been tracking line card/modules.  Until NetBox starts allowing for module/line card definition imports like it does for device types, it would be confusing to add those definitions here.  I'm open to discussing further.
