### ISSUE TITLE
Missing management interfaces for Juniper equipment

### ISSUE THREAD

**Issue by dovi5988** [netbox-community/devicetype-library#37]
Hi,

The management interface  is missing from the Juniper equipment. In addition there is a lot of other hardware not listed that I can easily create the templates for (other Juniper, equipment, PDU's etc.). Is there any docs on the format for the templates?

I am a b00b when it comes to github. I assume once I generate the files I can do a pull request?

**Comment by ryanmerolle** [comment]
Check out the documentation:

- [CONTRIBUTING](https://github.com/netbox-community/devicetype-library/blob/master/CONTRIBUTING.md)
- [README](https://github.com/netbox-community/devicetype-library/blob/master/README.md)

If you are noob to git/github and do not know how to clone, there is a ton of documentation online about forking, editing, and submitting pull requests to merge your changes into the repo.  The yaml files are pretty self explanatory, so feel free to copy and create a new yaml with the model number you are trying to add.  I should be adding some APC PDUs soon that will be a good guide for other PDUs.

You can also start with the simple process of browsing to the web page of an existing device you would like to update and clicking the edit/pencil icon.

For help or questions you can check [the netbox-discuss mailing list](https://groups.google.com/forum/#!forum/netbox-discuss), or join us in the #netbox Slack channel on [NetworkToCode](https://networktocode.slack.com/)
