### ISSUE TITLE
Interface POE

### ISSUE THREAD

**Issue by qaxi** [netbox-community/devicetype-library#380]
It would be nice to mark Ethernet interfaces with POE technology.

It could be done by two approaches - 

1. add it to type 
```
- name: GigabitEthernet1/0/1
  type: 1000base-t-poe
```

2. add variable
```
- name: GigabitEthernet1/0/1
  type: 1000base-t
  poe: poe
```

poe would reflect basic types of POE by common name or by IEEE standard

1. PoE - 802.3af
2. PoE+ (PoE plus) - 802.3at
3. 4PPoE - 802.3bt

I preffere the first aproach.

Question is if the same aproach could by applied in netbox itself too

**Comment by bobjacobsen** [comment]
If this is going to be done, it would also be helpful to have "provides" and "consumes" ("source" and "sink"?) indicated somehow so the direction of power flow is clear. Connections don't have to be type-to-type to be correct, so long as the source provides what the sink can consume.

**Comment by eduncan911** [comment]
I agree with both comments.

However, I vote for the 2nd option in the OP.  It would allow upgrades of existing complex networks, that now you can just flag a port as PoE and define the source/consumer, etc.

Also, I would like to add a 3rd set of options: PoE Type, as there are many now, as the OP also outlined.  I recommend defining different PoE protocols for a few reasons:

- Much like different Port speeds (ge, xg, etc), we have different wattage and voltages for PoE (15W, 30W, 60W, 90W, etc).
- Could be used down the road in the Power section to help calculate load.
- Backwards compatible by defining as an extra property

The only question is, how to define what version the port is operating at.  A few suggestions off the top of my head:

- poe, poe+, 4ppoe
-  802.3af, 802.3at 802.3bt

They would look like:

```
- name: ge-1/1/1
  type: 1000base-t
  poe: poe
- name: ge-1/1/2
  type: 1000base-t
  poe: 4ppoe
- name: ge-1/1/3
  type: 1000base-t
  poe: 4ppoe

// or

- name: ge-1/1/1
  type: 1000base-t
  poe: 802.3at
- name: ge-1/1/2
  type: 1000base-t
  poe: 802.3bt
- name: ge-1/1/3
  type: 1000base-t
  poe: 802.3bt
```

**Comment by ryanmerolle** [comment]
I'm not by my computer to test, but if I recall netbox will fail on the import given a unknown key.

The way I have done it with some devices like the Fortinet FG-81-POE is to add some comments where that is a valid key and use # to add comments to the ports saying it was Poe.  You could add a commented out poe key for each port also.  If and when POE is introduced to netbox, we can adjust the device type ports to use the proper key.

**Comment by qaxi** [comment]
So it is more NetBox feature request, it will come here as an "dependency" thing, is it?

**Comment by ryanmerolle** [comment]
So I just double checked.  I was wrong about the import failure on unknown keys.  Just because no model is set yet in NetBox, and I would prefer we not confuse users into thinking there is support and the POE key just did not import, I would recommend we follow the model I put in place first.  If all device-types follow this model, we can adjust later if/when NetBox comes out with POE support that does not match the model we crowdsourced.  Furthermore, the keys are commented out for now.

```bash
---
manufacturer: Fortinet
model: FortiGate 81E-POE
slug: fg-81e-poe
part_number: FG-81E-POE
u_height: 1
is_full_depth: false
comments: Same as FG-80E-POE , but **WITH** a 128GB SSD on-board.  Has 12 x 1G POE.
console-ports:
  - name: Console
    type: rj-45
power-ports:
  - name: PS1
    type: nema-5-15p
    maximum_draw: 137
    allocated_draw: 20
interfaces:
  - name: port1
    type: 1000base-t
    # poe: 802.3at
  - name: port2
    type: 1000base-t
    # poe: 802.3at
```

**Comment by ryanmerolle** [comment]
> So it is more NetBox feature request, it will come here as an "dependency" thing, is it?

Yea we want to follow what the main NetBox project supports and not confuse anyone.

**Comment by eduncan911** [comment]
Looks like there is a 4 year old issue in Netbox trying to implement it.

https://github.com/netbox-community/netbox/issues/1099
