### ISSUE TITLE
Importing devices from NetBox fails ...

### ISSUE THREAD

**Issue by qaxi** [netbox-community/devicetype-library#383]
Not sure it is real issue ...

### PROBLEM
I have a few devices in my NetBox (v2.10.10) and I wanted to include them to this repo.

And I found, that exporting NetBox devices is not that easy ...

You can fail at these tests ...

First you fail on yamlint:
```
$ yamllint -c tests/yamllint.yaml device-types/Cisco/SG250-10P-K9.yaml
device-types/Cisco/SG250-10P-K9.yaml
  1:1       warning  missing document start "---"  (document-start)
  9:1       error    wrong indentation: expected 2 but found 0  (indentation)
  12:1      error    wrong indentation: expected 2 but found 0  (indentation)
  17:1      error    wrong indentation: expected 2 but found 0  (indentation)
```
you have to edit file and make it YAML file (see 12dd3d43fea7d06a29709bf23d0979ac9eb006e3)

Than you can test if values are correct:

```
$ pytest -k SG250-10P-K9
```

NB can have (usually have) empty ('') subdevice_role in meaning "undefined", but DL requires exact value 
(see a0431db3a874188aaf91cae2d8a9b4905b625370)
```
Failed validating 'enum' in schema['properties']['subdevice_role']:
    {'enum': ['parent', 'child'], 'type': 'string'}
```

NB can have empty string ('') power-port type in meaning "undefined", but DL requires exact value (and there is no value "Other")
```
Failed validating 'enum' in schema['properties']['power-ports']['items']['properties']['type']:
... a long list ...
```
(see a4521283015f96a6c48a4dc95b4e32ddef7a31c1)

Other examples are "allocated_draw: null" - you need to delete it from NB export 
(IMHO majority of devices define only maximum_draw in documentation ... I saw only PoE devices to define draw with and without full PoE)
(see 20d1e443e08899a348c0284a8042cc09b429cf66)

May be it is minor problem, but for me it is annoying ... IMHO that extra work could prevent some contributors to finish their contribution.

### SOLUTION

Change tests or NetBox export (ideally both to share the same definition of output)

**Comment by jeremystretch** [comment]
These are excellent notes! Thanks for taking the time to put them together. I'm sure we can sand down some of the rough spots on the NetBox side. I think we just need to break each of these into discrete pieces and figure out the best way to handle each case.
