### ISSUE TITLE
Issue with Importing Device Types

### ISSUE THREAD

**Issue by ULHTNetbox** [netbox-community/devicetype-library#410]
I've tried to import the C6807-XL template but I get an error

Invalid YAML data: mapping values are not allowed here in "<unicode string>", line 98, column 65: ... e" content="{&quot;version&quot;: &quot;4&quot;, &quot;rollouts& ... ^

My Netbox version is 2.11.6

I've tried 3 other templates and get the same error.

Please can anyone help me fix this issue?

Thanks

**Comment by zholbrook** [comment]
I upgraded dev to 2.11.6 and was able to import the 6807 template fine. Can you provide anymore detail?

**Comment by danner26** [comment]
@ULHTNetbox were you able to get this resolved?
