### ISSUE TITLE
Questions about contributing various components

### ISSUE THREAD

**Issue by garbled1** [netbox-community/devicetype-library#46]
From the docs:
>  Include only components which are fixed to the chassis. Optional modular components should be omitted from the definition. (Note that this does not exclude field-replaceable hardware that is expected to always be present, such as power supplies.)

1. I have a Tripp-Lite PDU.  It has an optional SNMPWEBCARD installed.  Should I build it as a parent device, and also create a child for the card?

2. You have a generic 24p and 48p patch panel.  Do you want submissions for specific ones, such as a "Navepoint 24 port" or "Trendnet 48 port"?  What about ones that have 110-style punchdown instead of 8p8c?

3. Is there a specific way to deal with a device that has a shared port?  Say a switch that has 24 physical gige ports, and then 4 ports that are SFP+, but are "shared" with ports 21-24?

4. How would you prefer a device such as a 24 port keystone blank patch panel be added?  (there are near infinite options for those, so would it be best to just have a default of rj45 jacks and let people edit them post-install?)

Thanks!  This repo is great!

**Comment by jeremystretch** [comment]
> I have a Tripp-Lite PDU. It has an optional SNMPWEBCARD installed. Should I build it as a parent device, and also create a child for the card?

No, that is not a child device. It would be an inventory item, and outside the scope of the device type definition.

> You have a generic 24p and 48p patch panel. Do you want submissions for specific ones, such as a "Navepoint 24 port" or "Trendnet 48 port"? What about ones that have 110-style punchdown instead of 8p8c?

I think the generic ones were added primarily for testing. Just about any hardware that you can buy and install in your network is fair game.

> Is there a specific way to deal with a device that has a shared port? Say a switch that has 24 physical gige ports, and then 4 ports that are SFP+, but are "shared" with ports 21-24?

Unfortunately no; these are a pain to deal with. The current recommended approach is to define one of them and add a comment indicating that the user may desire to change the assigned type depending on the physical port in use. [Here](https://github.com/netbox-community/devicetype-library/blob/master/device-types/Fortinet/FG-100F.yaml) is an example.

**Comment by garbled1** [comment]
So how would you do the device setup for the PDU?  I want the PDU to properly show that there is a network connected and possibly even a console cable. The SNMPWEBCARD contains the ethernet and serial ports, and without them, the device has none.

Which is why I thought it was a child device, as then the "parent" can have the optional daughtercard that gives it network functionality, or without, it's just a simple PDU.

**Comment by jeremystretch** [comment]
You can just add the network interface; don't worry about defining the network card itself.

**Comment by garbled1** [comment]
Ok thanks!
