### ISSUE TITLE
part_number validation fail

### ISSUE THREAD

**Issue by walday** [netbox-community/devicetype-library#513]
part_number consisting of only numbers, without letters does not pass validation
example - 
https://hub.digi.com/support/products/infrastructure-management/digi-cm/
part_number: 70001949

**Comment by FloEisen** [comment]
You can use quotes to avoid syntax errors like stated in the [CONTRIBUTING.md](https://github.com/netbox-community/devicetype-library/blob/master/CONTRIBUTING.md)

**Comment by danner26** [comment]
Was this resolved for you? @walday
