### ISSUE TITLE
The name of this barrel plug

### ISSUE THREAD

**Issue by FacundoAcevedo** [netbox-community/devicetype-library#575]
Hi, I have the feeling that this is not the correct place for this question, but since I've been creating some devices an answer will improve the quality of my contributions.
I'm looking for the name in Netbox of this kind of power connector:
![](https://mla-s1-p.mlstatic.com/608409-MLA31787200012_082019-F.jpg)

Thanks

**Comment by FloEisen** [comment]
For this kind of plugs I used `dc-terminal` as type

**Comment by FacundoAcevedo** [comment]
Thank you very much
