### ISSUE TITLE
Newer dell servers have 'slot' cards for onboard nics. multiple options available

### ISSUE THREAD

**Issue by ITJamie** [netbox-community/devicetype-library#581]
Newer dell servers have 'slot' cards for onboard nics. multiple card options available. 1gb 10gb etc

If i put the effort into making a replacement yml file for this along with the 3 slot card options would this be accepted as a replacement for the likes of the dell r630 poweredge? 

doco: https://qrl.dell.com/Files/en-us/Html/Manuals/R630/Back-panel%20features%20and%20indicators=GUID-C0B66403-F253-407C-B50C-90391617E03A=1=en-us=.html 
search for ethernet connections.

**Comment by danner26** [comment]
Do you still need this? If you are willing to work on these changes then yes we will review and merge when ready
@ITJamie
