### ISSUE TITLE
Unknown properties are ignored during schema validation

### ISSUE THREAD

**Issue by michaelklose** [netbox-community/devicetype-library#616]
I have done some experiments with the new module-bays option and noticed, that unknown/misspelled properties are currently ignored during schema validation and doesn't raise a failure.

This can be fixed by adding "additionalProperties": false, to the schema.json file.

Currently I have noticed the following unknown properties in use:
comments
comment
power-port
console-server-port
console_ports
power_ports
full_depth

For reference I added my pytest results with modified schema.json.
[results.txt](https://github.com/netbox-community/devicetype-library/files/7797637/results.txt)

I can open a pull requests to fix this if the issue is accepted.

**Comment by ryanmerolle** [comment]
Good catch.  Please feel free to submit a PR

**Comment by michaelklose** [comment]
What about comments/comment should one of them added as a valid option?
