### ISSUE TITLE
Extend tests to check for null/empty values

### ISSUE THREAD

**Issue by jeremystretch** [netbox-community/devicetype-library#686]
We should extend the validation tests to flag any null or empty attribute definitions. For example, `description: ''` is unnecessary, since the attribute will default to an empty string. Explicitly specifying an empty value merely consumes space unnecessarily.

**Comment by michaelklose** [comment]
I I would like to work on that issue to update the validation tests and also clean up the existing templates.

**Comment by jeremystretch** [comment]
Thanks @michaelklose, I'll assign this to you!
