### ISSUE TITLE
Import Device/Module Type from this repository directly to Netbox (GUI Interface)

### ISSUE THREAD

**Issue by emersonfelipesp** [netbox-community/devicetype-library#704]
I have not found a Issue about it, sorry if it already exists.

But I think it would be pretty useful to have a way to import the **Device Types** and **Module Types** from this repository (devicetype-library) direct to Netbox. **To have a GraphicalUser Interface (GUI) so that users could easily import it**.

I don't think it is difficult to do it nowadays, but I believe there is Netbox users who barely know how to use GitHub or what YAML file is.

Let me know if this conversation already exists, or maybe if there's even development ongoing (ot at least motivation to do it).
I thought to maybe create a plugin to solve it.

**Comment by ryanmerolle** [comment]
@k01ek created a plugin for this https://github.com/k01ek/netbox-devicetype-importer
