### ISSUE TITLE
Question: Non data centre equipment

### ISSUE THREAD

**Issue by christopherkettell** [netbox-community/devicetype-library#86]
I have been working on a large field area network for roadside equipment (predominately Cisco). Equipment covers their ruggedised range of industrial ethernet switches, routers etc. Would these be a welcome addition to the device type library?

**Comment by ryanmerolle** [comment]
This is a community repo that focuses on allowing others to collaborate on common device models.  Though the benefiting audience would be smaller, I imagine this repo would be the right place to track it.

**Comment by ryanmerolle** [comment]
Closing this ticket out.  If you want to submit a PR for the equipment, I would be happy to review.
