### ISSUE TITLE
Missing models and vendors

### ISSUE THREAD

**Issue by vonv** [netbox-community/devicetype-library#906]
Hi. Thanks a lot for netbox, it's a huge handy tool !

Asking about the update process:
- i don't see the latest Juniper Switches models: EX4600,...
- i don't see either de products of Forcepoint vendor (firewalls for example): https://www.forcepoint.com/fr/appliance/forcepoint-ngfw-appliances

Is there a way to ask for updates ?

**Comment by DanSheps** [comment]
You submit a PR
